0	@NAME
1	@SEQ_NUMBER
2	@ID
3	4	LINK	dbsounds.dat:0	Sound ID	Sound ID	EDITABLE	KNOWN	BLACK
4	@UNKNOWN_FLOAT
5	@UNKNOWN_FLOAT
6	@UNKNOWN_FLOAT
7	@UNUSED_FLOAT
8	@UNKNOWN_FLOAT
9	@UNUSED_FLOAT
10	@UNUSED_FLOAT
11	@UNUSED_FLOAT
12	@UNKNOWN_INT4
13	@UNUSED_FLOAT
