0	@NAME
1	@SEQ_NUMBER
2	@ID
3	4	INTEGER	Shock mult	Shock mult	EDITABLE	KNOWN	BLACK
4	4	INTEGER	Arrow mult	Arrow mult	EDITABLE	KNOWN	BLACK
5	4	INTEGER	Pierce mult	Pierce mult	EDITABLE	KNOWN	BLACK
6	4	INTEGER	Gun mult	Gun mult	EDITABLE	KNOWN	BLACK
7	4	INTEGER	Laser mult	Laser mult	EDITABLE	KNOWN	BLACK
8	4	INTEGER	Missile mult	Missile mult	EDITABLE	KNOWN	BLACK
