0	@STRING_SIZE
1	0	DYNAMIC_STRING	0	Pathname	Pathname	EDITABLE	KNOWN	BLACK
2	@NAME
3	@SEQ_NUMBER
4	@ID
5	@UNKNOWN_INT4
6	@UNKNOWN_INT4
7	@UNKNOWN_INT4
8	@UNKNOWN_INT4
9	@UNKNOWN_INT4
10	@UNUSED_INT4
