0	4	FLOAT	Float/Min float	Float/Min float	EDITABLE	KNOWN	BLACK
1	4	FLOAT	Max float	Max float	EDITABLE	KNOWN	BLACK
2	@SEQ_NUMBER
3	4	ENUM	WorldID	ID	ID	BLOCKED	KNOWN	BLACK
4	4	INTEGER	Int/Min int	Int/Min int	EDITABLE	KNOWN	BLACK
5	4	INTEGER	Max int	Max int	EDITABLE	KNOWN	BLACK
6	@UNKNOWN_INT4
