0	@NAME
1	@SEQ_NUMBER
2	@ID
3	4	FLOAT	Cost	Cost	EDITABLE	KNOWN	BLACK
4	@ID_UNIT_SET
5	@ID_TECH
6	4	INTEGER	Set amount	Set amount	EDITABLE	KNOWN	BLACK
7	4	LINK	dbgfxeffects.dat:0	GFX Effect	GFX Effect	EDITABLE	KNOWN	BLACK
8	@UNUSED_INT4
9	4	FLOAT	Mod amount	Mod amount	EDITABLE	KNOWN	BLACK
10	@UNUSED_INT4
11	@UNUSED_INT4
12	@UNUSED_INT4
13	@ID_OBJECT
