0	@STRING_SIZE
1	0	DYNAMIC_STRING	0	Pathname	Pathname	EDITABLE	KNOWN	BLACK
2	@NAME
3	@SEQ_NUMBER
4	@ID
5	4	INTEGER	Color: Red	Color: Red	EDITABLE	KNOWN	BLACK
6	4	INTEGER	Color: Green	Color: Green	EDITABLE	KNOWN	BLACK
7	4	INTEGER	Color: Blue	Color: Blue	EDITABLE	KNOWN	BLACK
