0	@NAME
1	@SEQ_NUMBER
2	@ID
3	4	INTEGER	Font type	Font type	EDITABLE	KNOWN	BLACK
4	4	INTEGER	Font size	Font size	EDITABLE	KNOWN	BLACK
5	4	INTEGER	Quality	Quality	EDITABLE	KNOWN	BLACK
6	1	BOOLEAN	Bold	Bold	EDITABLE	KNOWN	BLACK
7	1	BOOLEAN	Italic	Italic	EDITABLE	KNOWN	BLACK
8	1	BOOLEAN	Underline	Underline	EDITABLE	KNOWN	BLACK
9	1	BOOLEAN	Has shadow	Has shadow	EDITABLE	KNOWN	BLACK
10	@UNUSED_INT4
